### ISSUE TITLE
Boost stuck on "Applying cache changes"

### ISSUE THREAD

**Issue by thomkrupa** [planetscale/boost-beta#4]
Hey, I created a couple of Boost Queries and they are stuck on "Applying cache changes" status. Is there a bug? Or is this just take some time to apply those changes?

<img width="1336" alt="Screenshot 2023-03-13 at 12 30 05" src="https://user-images.githubusercontent.com/8614811/224689837-125d4c8c-bdf7-4e54-afae-2d5ea847c433.png">

**Comment by nickvanw** [comment]
Hey @thomkrupa - thanks for reporting this! I will get this back to the team for a look. It is not expected that it takes this long, so there is likely a bug or problem applying the PlanetScale Boost cache.

**Comment by rbranson** [comment]
@thomkrupa Hey there, today we shipped a new version that fixes the bug you encountered. Your Boost instance is looking healthy now. Please let us know if you are still experiencing issues. Thanks for your patience!
